# Generated by Django 3.2.7 on 2021-09-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='major_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='single_day_delivery.hub'),
        ),
    ]
