# Generated by Django 3.2.7 on 2021-09-05 16:29

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0002_hub_major_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('bag_type', models.IntegerField(choices=[(0, 'Forward'), (1, 'Reverse')], default=0)),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'In Transit'), (2, 'Bag Received')], db_index=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bag_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Seller Received Order'), (2, 'In Transit'), (3, 'Order Received at Hub'), (4, 'Out for Delivery'), (5, 'Order Delivered')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Seller Received Order'), (2, 'In Transit'), (3, 'Order Received at Hub'), (4, 'Out for Delivery'), (5, 'Order Delivered')]),
        ),
    ]
