# Generated by Django 3.2.7 on 2021-09-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0003_auto_20210905_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='destination_type',
            field=models.IntegerField(choices=[(0, 'Society'), (1, 'Hub')], default=1),
        ),
        migrations.AlterField(
            model_name='hub',
            name='major_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='single_day_delivery.hub'),
        ),
    ]
