# Generated by Django 3.2.7 on 2021-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0004_auto_20210906_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'Hub Incharge'), (1, 'Customer'), (2, 'Driver'), (3, 'Delivery Partner'), (4, 'Shop Partner'), (5, 'Society Partner')], null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_type',
            field=models.IntegerField(blank=True, choices=[(2, 'Driver'), (3, 'Delivery Partner'), (4, 'Shop Partner'), (5, 'Society Partner')], null=True),
        ),
        migrations.AddField(
            model_name='sellershops',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
