# Generated by Django 3.2.7 on 2021-09-07 10:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0005_auto_20210907_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
