# Generated by Django 3.2.7 on 2021-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0006_constants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
