# Generated by Django 3.2.7 on 2021-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0008_auto_20210907_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='current_hub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binbagmapping',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='binbagmapping',
            unique_together={('bin_id', 'bag_id')},
        ),
    ]
