# Generated by Django 3.2.7 on 2021-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0009_auto_20210907_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='current_capacity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
