# Generated by Django 3.2.7 on 2021-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0010_alter_bin_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='sellershops',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
