# Generated by Django 3.2.7 on 2021-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0011_auto_20210908_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellershops',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
