# Generated by Django 3.2.7 on 2021-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0012_auto_20210908_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellershops',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
