# Generated by Django 3.2.7 on 2021-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0013_alter_sellershops_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('bag_code', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehicletransitdetails',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicletransitdetails',
            name='vehicle_number',
            field=models.CharField(default='KA51HK5041', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
