# Generated by Django 3.2.7 on 2021-09-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_day_delivery', '0014_auto_20210908_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='current_location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletransitdetails',
            name='received_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletransitdetails',
            name='transit_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
